
 import React, { useState } from 'react';
 import { StyleSheet, Text, View,ScrollView} from 'react-native';
 import  Mainstyles from '../../assets/style';
 import HeaderComponent from '../../components/CommonScreen/NoTitleHeader';
 import FixedNavbar from '../../components/CommonScreen/FixedNavbar'; 

 const TermsConditionScreen = ({navigation}) => {  
   const [selectedLanguage, setSelectedLanguage] = useState();
  return (
    <View>
      {/* Header */}
      <HeaderComponent  navigation={navigation} />
      <ScrollView showsVerticalScrollIndicator={false} style={{height:'100%'}}>

        {/* Divider */}
        <View style={Mainstyles.divider}></View>
        
        {/* Notification */}      
        <View style={styles.cartSection}>
          <View style={styles.cartBlock}>

            {/* About */}
            <View style={styles.cartItem}>
              <Text style={[styles.head,{marginTop:0}]}>GENERAL TERMS OF USE</Text>
              <Text style={styles.para}>These general terms of use (the "General Terms of Use") describe the terms on which the Users (defined hereunder) access, view, use and register on the Android app & Pyaas.in and any mobile or other application owned and/or operated by Pyaas or any of its Affiliates (defined hereinafter) ("Pyaas"), collectively referred to as the "Platform" Pyaas adheres strictly to the Information Technology Act, 2000 (hereinafter referred to as the "IT Act, 2000") and the rules framed there under. In order to ensure compliance with the above, Pyaas records that this document is an electronic record generated by a computer system and [does not require any physical or digital signatures]. Pyaas has established these General Terms of Use in order to inter alia ensure compliance with the provisions of Rule 3 (1) of the Information Technology (Intermediaries Guidelines) Rules, 2011. PLEASE READ THESE GENERAL TERMS OF USE CAREFULLY BEFORE ACCESSING, VIEWING, USING OR REGISTERING ON THE PLATFORM OR ACCESSING ANY MATERIAL, INFORMATION OR SERVICES THROUGH THE PLATFORM. USER'S ACCESS OR USE OF THE PLATFORM SHALL SIGNIFY USER'S UNCONDITIONAL ACCEPTANCE OF THE GENERAL TERMS OF USE AND USER'S AGREEMENT TO BE LEGALLY BOUND BY THE SAME. Your access or use of the Platform is governed by these General Terms of Use. If you transact on the Platform, You shall be subject to the policies that are applicable to the Platform for such a transaction. As long as you comply with these General Terms of Use, We grant you a non-exclusive, non-transferable, revocable and limited license to access and use the Platform.</Text>
              <Text style={styles.para}>
                1. Definitions
                The following defined terms shall have the meanings set out below, unless otherwise specified:
              </Text>
              <Text style={styles.para}>
                1. "Affiliate" shall mean any person, directly or indirectly, controlling, controlled by, or under common control with Pyaas. The term "control" shall include the right to appoint the majority of the directors or to control the management/ policy decisions exercisable by any person(s) acting individually.
              </Text>
              <Text style={styles.para}>
                2. "Products" shall mean the Drinking water cans which is listed and delivered by Pyaas on the Platform.
              </Text>
              <Text style={styles.para}>
                2. "We", "Us" and "Our" shall mean Pyaas.
              </Text>
              <Text style={styles.para}>
                4. "You", "Your", "Yourself" or "User" refers to a buyer, or any visitor on the Platform.
              </Text>

              <Text style={styles.head}>2. Account and Registration</Text>
              <Text style={styles.para}>
                1.You are encouraged to register on the Platform by creating an Account (as defined below), and providing such other details as necessary, including Phone number (OTP verification) your name (or the name of your business entity, as the case may be), address, email address.
              </Text>
              <Text style={styles.para}>
                2.In order to order water can, You must register with your mobile number on the Platform and create an account on the Platform, with a unique user identity and password (hereinafter referred to as "Account"). You may continue to order water until such time that you are registered on the Platform. You are responsible for maintaining the confidentiality of Your Account and the related details, and for restricting access to your computer and other electronic devices to prevent unauthorized access to Your Account. You agree to accept responsibility for all activities that occur under and in relation to Your Account (with or without your consent), and agree that Pyaas shall not be liable in any manner whatsoever. You agree to notify us immediately if you have any reason to believe that Your Account information has become known to anyone else, or if the Account is being, or is suspected of being, used in an unauthorized manner. You must ensure that you exit from Your Account at the end of each session. You may be held liable for losses incurred by Pyaas or any other User of the Platform due to any authorized or unauthorized use of Your Account for any reason attributable to You.
              </Text>
              <Text style={styles.para}>
                3. You shall not have more than 1 (one) active Account on the Platform at any point of time. Use of another User's Account information is expressly prohibited. You are also prohibited from transferring Your Account to another party.
              </Text>
              <Text style={styles.para}>
                4.You agree that if You provide any information which is untrue, inaccurate or incomplete, or if We have reasonable grounds to suspect that such information is untrue, inaccurate or incomplete, or if such information is not in accordance with these General Terms of Use, We shall have the right to indefinitely suspend, terminate or block You from accessing and using the Platform, and take such other action as We deem fit.
              </Text>
              <Text style={styles.para}>
                5.You must also inform us immediately in the event of any change in the information provided by you. You can also update the Account related information provided by you, by visiting the appropriate section in the app]. Pyaas reserves the right to restrict/ prohibit your access to the Platform and terminate your registration, at any time, without according any reason for doing so.
                </Text>
                
                
                
                <Text style={styles.head}>3. Eligibility</Text>
              <Text style={styles.para}>
                1. The use of the Platform is available only to persons who can enter into legally binding contracts under the Indian Contract Act, 1872. If you are a minor i.e. under the age of 18 (eighteen) years, you shall not register yourself as a User on the Platform or transact on the Platform. You represent that you are of legal age to form a binding contract, and are not a person barred from purchasing Products on the Platform under the applicable laws.
              </Text>
              <Text style={styles.para}>
                2.You must have the requisite resources, including internet access and equipment to access and use the Platform, and Pyaas shall not be liable or responsible for the same.
                </Text>
                
                <Text style={styles.head}>4. Obligations of Users</Text>
              <Text style={styles.para}>
                You must not use the Platform in any way that causes, or is likely to cause, the Platform or the access thereto to be interrupted, damaged or impaired in any way. You understand that you, and not Paanilao, are responsible for all electronic communications and content sent from your computer or other equipments and Your Account and You must use the Platform for lawful purposes only.
              </Text>
              <Text style={styles.para}>
                2.You must not use the Platform to publish or share any material without having the right to do so;
                </Text>
                
              <Text style={styles.para}>
                3. You must not use the Platform to host, display, upload, modify, publish, transmit, update, share, send, use or reuse any material/information that does not belong to You and You do not have any right to; or which is grossly harmful, illegal, offensive (including but not limited to material that is sexually explicit content or which promotes racism, bigotry, hatred or physical harm), deceptive, misleading, abusive, indecent, harassing, blasphemous, defamatory, libelous, obscene, pornographic, paedophilic or menacing; ethnically objectionable, hateful or racial, disparaging or in breach of any intellectual property including, but not limited to, patent, trademark, copyright or other proprietary rights, confidentiality, privacy or any other proprietary right/ information; or is otherwise injurious to third parties; or relates to or promotes money laundering or gambling; or is harmful to minors in any way; or impersonates another person; or threatens the unity, integrity, defence, security or sovereignty of India or its friendly relations with foreign states or causes incitement to the commission of any cognizable offence or prevents investigation of any offence or is insulting any other nation; or which is otherwise unlawful in any manner whatsoever; or which consists of or contains software viruses or any other computer code, files or programs designed to interrupt, destroy or limit the functionality of any computer resource; or which deceives or misleads the addressee about the origin of such messages or communicates any information which is grossly offensive or menacing in nature.
              </Text>
              <Text style={styles.para}>
                You must not use the Platform for fraudulent purposes, or in connection with any criminal offense or other unlawful activity;
                </Text>
              <Text style={styles.para}>
                You must not use the Platform to cause any commercial solicitation, chain letters, mass mailings or any 'spam' to cause annoyance, inconvenience or needless anxiety; or
              </Text>
              <Text style={styles.para}>
                You must not use the Platform to impersonate another person, or to deceive any other person about the origin of any communication, which is offensive.
              </Text>
              <Text style={styles.para}>
                You may send communications; and submit suggestions, ideas, comments, questions or other information, as long as the content is in compliance with these General Terms of Use.
              </Text>
              <Text style={styles.para}>
                You must not use any false e-mail address, impersonate any person or entity, or otherwise mislead any person as to the origin of any content. We reserve the right (but not the obligation) to remove or delete any such content that, in the sole judgment of Pyaas, violates these General Terms of Use and/or terminate your right to access or use the Platform.
                </Text>
                <Text style={styles.head}>
                5. Representations and Warranties of the Users
              </Text>
              <Text style={styles.para}>
                1.By visiting, viewing, accessing, installing, loading or using the Platform, You are providing unqualified acceptance to these General Terms of Use and any and all policies of Pyaas relating to the Platform;
              </Text>
              <Text style={styles.para}>
                2.You are of legal age and sound mind, and have accepted these General Terms of Use, without any undue force, pressure, influence or coercion;
              </Text>
              <Text style={styles.para}>
                3.By using the Platform, You are not violating any other terms, conditions or agreement to which You may be subject, and any law applicable to You;
                </Text>
                
              <Text style={styles.para}>
                4.You own or otherwise control all of the rights to the content that You post or that You otherwise provide on or through the Platform;
                You shall use the Platform only for lawful purposes;
              </Text>
              <Text style={styles.para}>
                5.As on the date that the content or material is submitted to Pyaas: (a) the content and material is accurate;
                (b) use of the content and material supplied by You does not breach any applicable policies of Pyaas or any applicable law, and 
                (c) the use of the content and material will not cause injury to any person or entity.
                </Text>
                <Text style={styles.head}>6. THIRD-PARTY SERVICES</Text>
              <Text style={styles.para}>
                In general, the third-party providers used by us will only Deliver water cans, collect, and disclose your information to the extent necessary to allow them to perform the services they provide to us.
              </Text>
              <Text style={styles.para}>
                However, certain third-party service providers, such as payment gateways and other payment transaction processors, have their own privacy policies in respect to the information we are required to provide to them for your purchase-related transactions.
              </Text>
              <Text style={styles.para}>
                For these providers, we recommend that you read their privacy policies so you can understand the manner in which your personal information will be handled by these providers.
              </Text>
              <Text style={styles.para}>
                In particular, remember that certain providers may be located in or have facilities that are located a different jurisdiction than either you or us. So if you elect to proceed with a transaction that involves the services of a third-party service provider, then your information may become subject to the laws of the jurisdiction(s) in which that service provider or its facilities are located.
                </Text>
              <Text style={styles.para}>
                Once you leave our App (Pyaas) or are redirected to a third-party website or application, you are no longer governed by this Privacy Policy Terms of Service.
                </Text>
                <Text style={styles.head}>7. Feedbacks and Reviews</Text>
              <Text style={styles.para}>
                1.You may provide feedback in relation to the use of the Platform and Products. You agree to provide honest feedback, review and comments, and support the same with sufficient evidence as required by us.
              </Text>
              <Text style={styles.para}>
                2.You are not in breach of any obligation (legal, contractual or otherwise) by sharing such feedback with us, and that you are not entitled to any compensation for provision of such feedback.
              </Text>
              <Text style={styles.para}>
                3. When You provide any feedback on the Platform, You grant to Pyaas, a non-exclusive, royalty-free, worldwide, transferable, irrevocable, perpetual and unconditional license to
                (a) use, and share Your feedback as We deem fit, including to the User to whom such feedback relates; and
                (b) remove whole or part of the feedback, which We may consider to be defamatory, in breach of applicable laws or these General Terms of Use.
                </Text>
                <Text style={styles.head}>8. Termination</Text>
              <Text style={styles.para}>
                1.You shall, at all times, be bound by these General Terms of Use. You may however choose to terminate your arrangement under these General Terms of Use by closing Your Account, and thereafter ceasing to use the Platform.
                </Text>
              <Text style={styles.para}>
                2.Paanilao reserves a right to forthwith terminate Your arrangement (without any liability) under these General Terms of Use, without notice to You, if: a) You breach any of these General Terms of Use; b) Such termination is required under any applicable law; and c) For any other reason, as Paanilao may deem fit.
              </Text>
              <Text style={styles.para}>
                1.Paanilao may also block your future access/ use of the Platform. In addition, you also agree that any violation of these General Terms of Use by You will cause irreparable harm to Paanilao, for which monetary damages may be inadequate. You therefore agree that Paanilao is entitled to any injunctive or other equitable relief as may be applicable. These remedies are in addition to any other remedies that Paanilao may have at law or in equity.
              </Text>
              <Text style={styles.para}>
                2.In the alternative, Paanilao may choose to temporarily suspend access to the Platform, and/or Your Account for any breach of these General Terms of Use.
              </Text>
              <Text style={styles.para}>
                3.In case of any termination, you shall immediately fulfill your pending obligations/ liabilities towards Paanilao and/or any other User, resulting from use of the Platform.
                </Text>
                <Text style={styles.head}>9. Water Cans Deposit</Text>
              <Text style={styles.para}>
                Water Cans deposit collected Pyaas and Customer, therefore, Pyaas is liable to charge or deposit any taxes applicable on such transaction. In the event of discontinuation of service from Pyaas, Customer have to contact the pyaas for the refund, Pyaas assist you to the best of our abilities by providing relevant information to you, how to proceed.
              </Text>
              <Text style={styles.para}>
                Customer is liable for return /exchange of water cans in the condition they received during delivery, if failed to meet the terms result in pay the deposit for the new water.
                </Text>
                
                <Text style={styles.head}>10. Delivery Policy</Text>
              <Text style={styles.para}>
                Pyaas aim to deliver the water cans with best in effort to delivery on the time slot selected by customers on the time of delivery. Changing of delivery time slot is not permitted after the order is confirmed.
              </Text>
              <Text style={styles.para}>At present Pyaas provide two convenient slots</Text>
              <Text style={styles.para}>Morning: 9 AM to 01 PM </Text>
                <Text  style={styles.para}>
                Evening: 3 PM to 7 PM.</Text>
                <Text  style={styles.para}>Please note that the delivery slot is changeable by Pyaas </Text>

                <Text  style={styles.head}>11. Amendment to the General Terms of Use</Text>
                <Text  style={styles.para}>
                1.Your use of and access to the Platform is offered on the condition that You unconditionally accept all the terms and conditions provided in these General Terms of Use, along with any amendments made by Pyaas at its sole discretion, from time to time, and posted on the Platform. Pyaas shall not be required to notify you, whether as a registered User or not, of any changes made to these General Terms of Use.
                </Text>
                <Text  style={styles.para}>
                2. Once the revised General Terms of Use are made available on the Platform, Your continued use of the Platform shall be construed to be your deemed acceptance of the revised General Terms of Use. Please regularly visit the Platform to view the most current General Terms of Use, which can be determined by the "Last Updated" legend above.
                </Text>

                <Text  style={styles.head}>12. Miscellaneous</Text>
                <Text  style={styles.para}>
                1.Severability: - If any provision contained in these General Terms of Use is deemed void, invalid or unlawful, such a provision shall be deemed severable from the remaining terms hereunder, which remaining terms will continue in full force and effect.
                </Text>
                <Text  style={styles.para}>
                2.Force Majeure: - Pyaas will not be held responsible for any delay or failure to comply with our obligations hereunder, if the delay or failure arises from any cause which is beyond our reasonable control.
                </Text>
                <Text  style={styles.para}>
                3.Waiver: - If you breach these General Terms of Use and if we do not take any action, it does not mean that we have waived our rights and remedies hereunder or under any applicable laws. Any waiver shall be deemed effective only when made in writing.
                </Text>
                <Text  style={styles.para}>
                4.Assignment: - You cannot assign or otherwise transfer any of your rights/ obligations under General Terms of Use to any third party. Pyaas may however freely transfer the same to any third party, without your consent.
                </Text>
                <Text  style={styles.para}>
                5.Relationship between Pyaas and You: - Pyaas and You are independent parties, and nothing in these General Terms of Use will be construed to create a partnership, joint venture, agency, franchise, or employment relationship between the parties. You will have no authority to make or accept any offers or representations on our behalf. You will not make any statement that would contradict anything in this Clause. These General Terms of Use will not create an exclusive relationship between you and us.
                </Text>
                <Text  style={styles.para}>
                6.Governing Law and Jurisdiction: - These General Terms of Use shall be governed by the laws of India. Any disputes arising out of or in relation to these General Terms of Use, or any transactions entered into on or through the Platform or the relationship between You and Pyaas, shall be subject to the exclusive jurisdiction of the Courts in Guwahati.
                </Text>
                <Text  style={styles.para}>
                7.Notices: For any queries relating to the Platform, You can reach out to us at contact-us.
                </Text>

                <Text  style={styles.head}>13. Additional Terms of Use</Text>
                <Text  style={styles.para}>
                1.Pyaas is not responsible for causing any delay in case of Delivery of Water cans within the delivery slot requested by you, at the time of placing order. It may get delayed due to various reasons for example extreme weather condition and govt. Rules which is beyond human control.
                </Text>
                <Text  style={styles.para}>
                2.Re-arrange the delivery time will be done as early as possible.
                </Text>
                <Text  style={styles.head}>
                14. Refund Policy
                </Text>
                <Text  style={styles.para}>
                You have full rights to deny the water can if it was physically damaged, contains foreign objects or any concerns with the water can, on the time of delivery. Accepted delivery of cans will not be eligible for the refund.
                </Text>
                <Text  style={styles.para}>
                  
                You shall be entitled to a refund only if you paid for your order at the time of placing your order on the Mobile App and only in the event of any of the following conditions, You will be required to share the proof of the same before any resolution can be provided by the delivery partners.
                </Text>
                <Text  style={styles.para}>
                (a). Water can was delivered in a physically damaged condition
                (b). Water can contain any foreign objects
                (c) .We cancelling your order due to below circumstances
                Your delivery location following outside our designated delivery area.
                Failure to contact you by phone or Messages (sms \ whatsapp) at the time of confirming the order booking.
                </Text>
                <Text  style={styles.para}>
                Please write us with registered mobile number and order number to pyaasapp60037 37738
                </Text>               

                <Text  style={styles.head}>
                15. Membership policies
                </Text>
                <Text  style={styles.para}>
                If you wish to cancel the membership, you may do so before your order is delivered for the first time.
                </Text>
                <Text  style={styles.para}>
                In case you might remain absent in your location at the time we deliver your order, you need to inform us beforehand about your absence. If our delivery executive is already out for delivery into your location with any knowledge of your absence then a jar for the day will be deducted from your account even if you do not receive it.
                </Text>
                <Text  style={styles.para}>
                Brands cannot be changed after your membership is confirmed. However you can always feel free to contact our customer care for any assistance.
                </Text>
                <Text  style={styles.para}>
                Delivery slots cannot be changed. However you can call the support if you want get your order delivered on a different slot. This facility is available only for that specific day and will not be entertained in the following days.
                </Text>
                <Text  style={styles.para}>
                Delivery frequency cannot be changed
                </Text>
                <Text  style={styles.para}>
                Refund option is available only if you cancel your membership before your oder is delivered for the first time.
                </Text>
                <Text  style={styles.para}>

                Quantity cannot be changed under any circumstances.
                </Text>

                <Text  style={styles.head}>
                16. Single orders
                </Text>
                <Text  style={styles.para}>
                You may cancel your order only before your order is out for delivery.
                </Text>
                <Text  style={styles.para}>
                Refund is available if order is cancelled before dispatching in 7-10 days.
                </Text>
                <Text  style={styles.para}>
                Brand cannot be changed after placement of orders.
                </Text>
                <Text  style={styles.para}>
                You can change the time slot before your order is dispatched.
                </Text>
                <Text  style={styles.head}>
                17. Delivery
                </Text>
                <Text  style={styles.para}>
                At any point of time, to ensure sanity and security our delivery partners will not enter your house to delivery your order.
                </Text>
                <Text  style={styles.para}>

                Delivery is chargeable from third floor onwards @ Rs 5 per jar. However in case lift or elevator facility is available then it is not chargeable in case of upper floors.
                </Text>

                <Text  style={styles.head}>
                18. Bulk orders
                </Text>
                <Text  style={styles.para}>

                If you order 20 litres jar or above you need to pay a security deposit for the jars which will be refunded at the time of delivery. Additionally if you already have the exact amount of empty jars as you ordered then no security deposit is required.
                </Text>
                <Text  style={styles.para}>
                For confirmation of bulk orders you need to pay us in advance and for this you need to call our customer care.
                </Text>
                <Text  style={styles.para}>
                In bulk orders the order need to be cancelled before 24 hours for availing full refund.
                </Text>
                <Text  style={styles.para}>
                If you cancel your order after it has been already dispatched the 50% of the payment already made by you , whatever amount it may be will be withheld and 50% will be refunded.
                </Text>
                <Text  style={styles.para}>
                You can change the brand, time slot and quantity before your order is dispatched.
                </Text>
            </View>           

            {/* Divider */}
            <View style={[Mainstyles.divider, { paddingBottom: 120 }]}></View>

          </View>
          
        </View>
      </ScrollView>

      {/* Fixed Navbar */}
      <FixedNavbar navigation={navigation} style={styles.FixedNavbar} />

    </View>

  );
};
const styles = StyleSheet.create({
  header: { justifyContent: 'center', alignItems:'center', paddingLeft: 10, paddingRight:10, paddingBottom:10, backgroundColor:'#fff', shadowColor: "#000", shadowOffset: {width: 0, height: 4,}, shadowOpacity: 0.30, shadowRadius: 4.65, elevation: 10,},
  
  headerText: {fontSize:30, fontWeight:"700",color:'#fff'},
  headerRow : {flexDirection: 'row',justifyContent:'space-between',width:'100%'},

  cartSection: {backgroundColor:'#eee', shadowColor: "#000", shadowOffset: {width: 0, height: 4,}, shadowOpacity: 0.30, shadowRadius: 4.65, elevation: 8},
  cartBlock: {flexDirection:'row',flexWrap:'wrap',borderRadius:5,paddingHorizontal:5},
  cartItem: {flexDirection:'column',width:"100%",backgroundColor:'#fff',padding:10, borderWidth: 1, borderColor: '#ddd', borderRadius:10,},
  cartPointText: {fontSize:8,color:'green',fontWeight:'700',marginBottom:-3},
  head: {fontSize: 18,color:'#333',fontWeight:'700',marginBottom:5, marginTop:8},
  para: {fontSize: 11,fontWeight:"500",color:'#000', textAlign:'justify'},
  
  cartItemBtnBlock: {marginVertical:5, flexDirection:'row',alignItems:'center'},
  statusHeader: {fontSize:12,color:'#333',fontWeight:'700'},
  statusBtn: {fontSize:12,paddingHorizontal:10,fontWeight:'700'},
})

export default TermsConditionScreen;
